version: '3.8'

services:
  rust-dev:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    command: tail -f /dev/null

volumes:
  cargo-cache:
